[project]
name = "tfm-ecorl"
version = "0.1.0"
description = "Repository for Master Thesis: Learning to Learn in Two-Armed Bandit Tasks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ml-collections>=1.1.0",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "torch>=2.10.0",
    "tqdm>=4.66.0",
    # Optional packages (not used fot TFM, extra material)
    "umap-learn>=0.5.12",
    "optax>=0.2.7",
    "dm-haiku",
    "rlax>=0.1.8",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
dm-haiku = { git = "https://github.com/deepmind/dm-haiku.git" }
